name: Docker

on:
  push:
    # run only against tags
    #tags:
    #  - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Interplanetary Container Registry
        uses: docker/login-action@v2
        with:
          registry: ipcr.io
          username: foo
          password: bar

      - name: Get the version (git tag)
        id: get_version
        run: |
          echo ${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build and push
        run: |
          docker build -t toybox .
          docker tag toybox ipcr.io/toybox:v1
          docker push ipcr.io/toybox:v1
