name: Docker

on:
  push:
    # run only against tags
    #tags:
    #  - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        run: |
          docker build -t toybox .
          docker tag toybox ipcr.io/toybox:v1
          docker push ipcr.io/toybox:v1
